// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArx6X0d4chhN1RBPXKLPvWHn3HkrqNGMk',
    appId: '1:885795244151:web:f0e9012b40e44891781e72',
    messagingSenderId: '885795244151',
    projectId: 'fire-ilk-proje',
    authDomain: 'fire-ilk-proje.firebaseapp.com',
    storageBucket: 'fire-ilk-proje.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ7eg0cxOWMsEeOVKCNRF9LoY9O-17D6A',
    appId: '1:885795244151:android:b1ccad8413173dc7781e72',
    messagingSenderId: '885795244151',
    projectId: 'fire-ilk-proje',
    storageBucket: 'fire-ilk-proje.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQLhmmEYOSbDY-zSm3QAoTCjK3R1LdLKQ',
    appId: '1:885795244151:ios:daa6a4d9202c9952781e72',
    messagingSenderId: '885795244151',
    projectId: 'fire-ilk-proje',
    storageBucket: 'fire-ilk-proje.appspot.com',
    iosClientId: '885795244151-pc8umcjg0uugnfd35ptcgaetlsbhicok.apps.googleusercontent.com',
    iosBundleId: 'com.star.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQLhmmEYOSbDY-zSm3QAoTCjK3R1LdLKQ',
    appId: '1:885795244151:ios:a2e30ba9b75f0c80781e72',
    messagingSenderId: '885795244151',
    projectId: 'fire-ilk-proje',
    storageBucket: 'fire-ilk-proje.appspot.com',
    iosClientId: '885795244151-otd8gg6i09qe83ujjs1sagufu2kvpjpb.apps.googleusercontent.com',
    iosBundleId: 'com.star.macapp',
  );
}
